"""baseline schema

Revision ID: 95097dc96149
Revises: 
Create Date: 2026-06-12 15:59:10.462498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95097dc96149'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('performed_by_name', sa.String(length=200), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created', 'audit_log', ['created_at'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.String(length=100), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.Column('pin', sa.String(length=10), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('paypakka_id', sa.String(length=100), nullable=True),
    sa.Column('imported_at', sa.String(length=100), nullable=True),
    sa.Column('surrendered_date', sa.String(length=100), nullable=True),
    sa.Column('surrender_reason', sa.String(length=500), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_index('idx_customers_area', 'customers', ['area'], unique=False)
    op.create_index('idx_customers_operator_id', 'customers', ['operator_id'], unique=False)
    op.create_index('idx_customers_phone', 'customers', ['phone'], unique=False)
    op.create_index('idx_customers_status', 'customers', ['status'], unique=False)
    op.create_table('notification_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key', 'operator_id')
    )
    op.create_table('online_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.Column('captured_at', sa.String(length=100), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('mso', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('license_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('customer_prefix', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paypakka_customer_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('cust_plan_ref_id', sa.String(length=100), nullable=True),
    sa.Column('plan_ref_id', sa.String(length=100), nullable=True),
    sa.Column('service_ref_id', sa.String(length=100), nullable=True),
    sa.Column('activate_date', sa.String(length=100), nullable=True),
    sa.Column('expired_date', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('paypakka_created_at', sa.String(length=100), nullable=True),
    sa.Column('paypakka_updated_at', sa.String(length=100), nullable=True),
    sa.Column('imported_at', sa.String(length=100), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paypakka_employees',
    sa.Column('emp_ref_id', sa.String(length=100), nullable=False),
    sa.Column('emp_name', sa.String(length=200), nullable=True),
    sa.Column('emp_role', sa.String(length=100), nullable=True),
    sa.Column('emp_status', sa.String(length=50), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('emp_ref_id')
    )
    op.create_table('paypakka_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('payment_ref_id', sa.String(length=100), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('service_ref_id', sa.String(length=100), nullable=True),
    sa.Column('plan_amount', sa.Float(), nullable=True),
    sa.Column('bill_amount', sa.Float(), nullable=True),
    sa.Column('collection_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('paypakka_created_at', sa.String(length=100), nullable=True),
    sa.Column('imported_at', sa.String(length=100), nullable=True),
    sa.Column('emp_ref_id', sa.String(length=100), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paypakka_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paypakka_plan_id', sa.String(length=100), nullable=True),
    sa.Column('plan_name', sa.String(length=200), nullable=True),
    sa.Column('plan_amount', sa.Float(), nullable=True),
    sa.Column('package_category', sa.String(length=100), nullable=True),
    sa.Column('billing_cycle', sa.String(length=50), nullable=True),
    sa.Column('billing_type', sa.String(length=50), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('mso', sa.String(length=50), nullable=True),
    sa.Column('sd_count', sa.Integer(), nullable=True),
    sa.Column('hd_count', sa.Integer(), nullable=True),
    sa.Column('inclusive_of_tax', sa.Integer(), nullable=True),
    sa.Column('plan_validity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('distributor_ref_id', sa.String(length=100), nullable=True),
    sa.Column('paypakka_created_at', sa.String(length=100), nullable=True),
    sa.Column('imported_at', sa.String(length=100), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('network', sa.String(length=50), nullable=True),
    sa.Column('mso_cost', sa.Float(), nullable=True),
    sa.Column('mso_cost_late', sa.Float(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('p256dh', sa.String(length=200), nullable=True),
    sa.Column('auth', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_no', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('tg_message_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.String(length=100), nullable=True),
    sa.Column('closed_at', sa.String(length=100), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.String(length=100), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_at', sa.String(length=100), nullable=True),
    sa.Column('on_the_way_at', sa.String(length=100), nullable=True),
    sa.Column('ack_lat', sa.Float(), nullable=True),
    sa.Column('ack_lng', sa.Float(), nullable=True),
    sa.Column('otw_lat', sa.Float(), nullable=True),
    sa.Column('otw_lng', sa.Float(), nullable=True),
    sa.Column('settled_lat', sa.Float(), nullable=True),
    sa.Column('settled_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.String(length=100), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stb_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stb_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('added_at', sa.String(length=100), nullable=True),
    sa.Column('added_by', sa.String(length=200), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surrender_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('stb_no', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('requested_by_name', sa.String(length=200), nullable=True),
    sa.Column('requested_at', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_name', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.String(length=100), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('stb_no', sa.String(length=50), nullable=False),
    sa.Column('can_id', sa.String(length=50), nullable=True),
    sa.Column('mso', sa.String(length=50), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('billing_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.Column('plan_name', sa.String(length=200), nullable=True),
    sa.Column('plan_amount', sa.Float(), nullable=True),
    sa.Column('activation_date', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.String(length=100), nullable=True),
    sa.Column('network', sa.String(length=50), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.String(length=100), nullable=True),
    sa.Column('disconnect_date', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connections_customer_id', 'connections', ['customer_id'], unique=False)
    op.create_index('idx_connections_operator_id', 'connections', ['operator_id'], unique=False)
    op.create_index('idx_connections_status', 'connections', ['status'], unique=False)
    op.create_table('customer_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('start_date', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_by_name', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.Column('last_activity', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_session_id', 'active_sessions', ['session_id'], unique=False)
    op.create_index('idx_sessions_user_id', 'active_sessions', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('collected_by', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.String(length=100), nullable=True),
    sa.Column('month_year', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('previous_balance', sa.Float(), nullable=True),
    sa.Column('bill_amount', sa.Float(), nullable=True),
    sa.Column('months_paid', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.String(length=100), nullable=True),
    sa.Column('delete_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_cust_month', 'payments', ['customer_id', 'month_year'], unique=False)
    op.create_index('idx_payments_op_collected', 'payments', ['operator_id', 'collected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payments_op_collected', table_name='payments')
    op.drop_index('idx_payments_cust_month', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_sessions_user_id', table_name='active_sessions')
    op.drop_index('idx_sessions_session_id', table_name='active_sessions')
    op.drop_table('active_sessions')
    op.drop_table('users')
    op.drop_table('request_timeline')
    op.drop_table('customer_plans')
    op.drop_index('idx_connections_status', table_name='connections')
    op.drop_index('idx_connections_operator_id', table_name='connections')
    op.drop_index('idx_connections_customer_id', table_name='connections')
    op.drop_table('connections')
    op.drop_table('surrender_requests')
    op.drop_table('stb_inventory')
    op.drop_table('sms_log')
    op.drop_table('service_requests')
    op.drop_table('push_subscriptions')
    op.drop_table('plans')
    op.drop_table('paypakka_plans')
    op.drop_table('paypakka_payments')
    op.drop_table('paypakka_employees')
    op.drop_table('paypakka_customer_plans')
    op.drop_table('operators')
    op.drop_table('online_payments')
    op.drop_table('notification_settings')
    op.drop_index('idx_customers_status', table_name='customers')
    op.drop_index('idx_customers_phone', table_name='customers')
    op.drop_index('idx_customers_operator_id', table_name='customers')
    op.drop_index('idx_customers_area', table_name='customers')
    op.drop_table('customers')
    op.drop_table('customer_auth')
    op.drop_table('complaints')
    op.drop_index('idx_audit_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
