// Common / shared UI translations
export default {
  'Save': 'சேமி',
  'Save Changes': 'மாற்றங்களை சேமி',
  'Cancel': 'ரத்து',
  'Close': 'மூடு',
  'Delete': 'நீக்கு',
  'Edit': 'திருத்து',
  'Add': 'சேர்க்க',
  'Search': 'தேடு',
  'Search…': 'தேடு…',
  'Loading…': 'ஏற்றுகிறது…',
  'Loading': 'ஏற்றுகிறது',
  'Error': 'பிழை',
  'Success': 'வெற்றி',
  'Back': 'பின்',
  'Next': 'அடுத்து',
  'Previous': 'முந்தைய',
  'All': 'அனைத்தும்',
  'None': 'எதுவும் இல்லை',
  'Name': 'பெயர்',
  'Phone': 'தொலைபேசி',
  'Mobile': 'மொபைல்',
  'Address': 'முகவரி',
  'Status': 'நிலை',
  'Active': 'செயலில்',
  'Inactive': 'செயலற்றது',
  'Disconnected': 'இணைப்பு துண்டிக்கப்பட்டது',
  'Connected': 'இணைக்கப்பட்டது',
  'Pending': 'நிலுவையில்',
  'Amount': 'தொகை',
  'Total': 'மொத்தம்',
  'Date': 'தேதி',
  'Type': 'வகை',
  'Notes': 'குறிப்புகள்',
  'Actions': 'செயல்கள்',
  'View All': 'அனைத்தையும் காண்க',
  'View': 'பார்க்க',
  'Send': 'அனுப்பு',
  'Retry': 'மீண்டும் முயற்சிக்கவும்',
  'Yes': 'ஆம்',
  'No': 'இல்லை',
  'Today': 'இன்று',
  'Yesterday': 'நேற்று',
  'Month': 'மாதம்',
  'Year': 'ஆண்டு',
  'Months': 'மாதங்கள்',
  'Copy': 'நகலெடு',
  'Copied!': 'நகலெடுக்கப்பட்டது!',
  'Optional': 'விருப்பம்',
  'Required': 'கட்டாயம்',
  'Show': 'காட்டு',
  'Hide': 'மறை',
  'Filter': 'வடிகட்டு',
  'Clear': 'அழி',
  'No results': 'முடிவுகள் இல்லை',
  'No data': 'தரவு இல்லை',
  'Something went wrong': 'ஏதோ தவறு நடந்தது',
  'Please try again': 'மீண்டும் முயற்சிக்கவும்',
  'Success!': 'வெற்றி!',
  'Failed': 'தோல்வி',
  'Enabled': 'இயக்கப்பட்டது',
  'Disabled': 'முடக்கப்பட்டது',
  'On': 'ஆன்',
  'Off': 'ஆஃப்',
  'Confirm': 'உறுதிப்படுத்து',
  'MSO': 'MSO',
} as Record<string, string>;
