// customers translations (Customers, CustomerDetail, AddCustomer, Connections, Surrender pages)
const customers: Record<string, string> = {
  // Customers list
  '{n} customer total': '{n} வாடிக்கையாளர் மொத்தம்',
  '{n} customers total': '{n} வாடிக்கையாளர்கள் மொத்தம்',
  'Search by name, phone, or STB number...': 'பெயர், தொலைபேசி அல்லது STB எண்ணில் தேடு...',
  'All Status': 'அனைத்து நிலைகள்',
  'Loading...': 'ஏற்றுகிறது...',
  'No customers found': 'வாடிக்கையாளர்கள் இல்லை',
  'Plan': 'திட்டம்',
  'Area': 'பகுதி',
  'Prev': 'முந்தைய',
  'Page {n} of {total}': 'பக்கம் {n} / {total}',
  // Customer detail
  'Surrendered': 'திருப்பி ஒப்படைக்கப்பட்டது',
  'Pending Surrender': 'திருப்பி ஒப்படைப்பு நிலுவையில்',
  'Unknown': 'தெரியவில்லை',
  'Set location on map': 'வரைபடத்தில் இடம் குறிக்க',
  'Edit Customer': 'வாடிக்கையாளரை திருத்து',
  'Saving...': 'சேமிக்கிறது...',
  'Phone 2': 'தொலைபேசி 2',
  'Customer Info': 'வாடிக்கையாளர் தகவல்',
  'Expiry Date': 'காலாவதி தேதி',
  'Connections ({n})': 'இணைப்புகள் ({n})',
  'Connection': 'இணைப்பு',
  'Plan Amount': 'திட்டத் தொகை',
  'Payment History': 'பணம் செலுத்திய வரலாறு',
  'STB Number': 'STB எண்',
  'Exchange STB': 'STB மாற்று',
  'Swap': 'மாற்று',
  'Restore Connection': 'இணைப்பை மீட்டெடு',
  'Restore': 'மீட்டெடு',
  'GTPL Operations': 'GTPL செயல்பாடுகள்',
  'Suspend': 'இடைநிறுத்து',
  'Activate': 'செயல்படுத்து',
  'Refresh STB signal — clears E-51 error after payment': 'STB சிக்னலை புதுப்பி — பணம் செலுத்திய பின் E-51 பிழையை நீக்கும்',
  'Retrigger': 'மீண்டும் தூண்டு',
  '{m} mo': '{m} மாதம்',
  'Renew': 'புதுப்பி',
  'Plan code': 'திட்ட குறியீடு',
  'Change Plan': 'திட்டம் மாற்று',
  'Checking...': 'சரிபார்க்கிறது...',
  'No payment history': 'பணம் செலுத்திய வரலாறு இல்லை',
  'Surrender Customer?': 'வாடிக்கையாளரை திருப்பி ஒப்படைக்கவா?',
  'This will surrender': 'இது திருப்பி ஒப்படைக்கும்',
  'All STBs will be freed and moved to inventory. The customer status will change to "Surrendered".': 'அனைத்து STB களும் விடுவிக்கப்பட்டு இருப்புக்கு நகர்த்தப்படும். வாடிக்கையாளர் நிலை "திருப்பி ஒப்படைக்கப்பட்டது" ஆக மாறும்.',
  'Reason (optional)': 'காரணம் (விருப்பம்)',
  'Surrendering...': 'திருப்பி ஒப்படைக்கிறது...',
  'Swap STB': 'STB மாற்று',
  'Current STB:': 'தற்போதைய STB:',
  'Select New STB from Inventory': 'இருப்பில் இருந்து புதிய STB தேர்வு செய்யவும்',
  'Select an STB': 'STB தேர்வு செய்யவும்',
  'No STBs available in inventory. Surrender a customer first to add STBs.': 'இருப்பில் STB இல்லை. முதலில் ஒரு வாடிக்கையாளரை திருப்பி ஒப்படைக்கவும்.',
  'Old STB ({stb}) goes to inventory as:': 'பழைய STB ({stb}) இருப்புக்கு இவ்வாறு செல்கிறது:',
  'Faulty (needs repair)': 'பழுது (பழுது பார்த்தல் தேவை)',
  'Spare (working, reusable)': 'உதிரி (செயல்படும், மீண்டும் பயன்படுத்தலாம்)',
  'MSO Portal Sync': 'MSO போர்டல் ஒத்திசைவு',
  'Auto-sync MSO portal': 'MSO போர்டலை தானாக ஒத்திசை',
  'Will suspend old + activate new': 'பழையதை இடைநிறுத்தி புதியதை செயல்படுத்தும்',
  'DB only, no portal sync': 'DB மட்டும், போர்டல் ஒத்திசைவு இல்லை',
  'Swapping...': 'மாற்றுகிறது...',
  'Swap Box': 'STB மாற்று',
  'STB Swapped: {old} → {new} ({mso})': 'STB மாற்றப்பட்டது: {old} → {new} ({mso})',
  'Old box suspended': 'பழைய பெட்டி இடைநிறுத்தப்பட்டது',
  'New box activated': 'புதிய பெட்டி செயல்படுத்தப்பட்டது',
  'Dismiss': 'மறை',
  'Old STB:': 'பழைய STB:',
  'Old box is available in inventory — can restore with same box': 'பழைய பெட்டி இருப்பில் உள்ளது — அதே பெட்டியுடன் மீட்டெடுக்கலாம்',
  'Old box not available — choose a different box below': 'பழைய பெட்டி இல்லை — கீழே வேறு பெட்டியை தேர்வு செய்யவும்',
  'Select STB from Inventory': 'இருப்பில் இருந்து STB தேர்வு செய்யவும்',
  'No available STBs in inventory. Add one first.': 'இருப்பில் STB இல்லை. முதலில் ஒன்றை சேர்க்கவும்.',
  'old box': 'பழைய பெட்டி',
  'Done': 'முடிந்தது',
  'Restoring...': 'மீட்டெடுக்கிறது...',
  'Delete Customer?': 'வாடிக்கையாளரை நீக்கவா?',
  'This will permanently delete': 'இது நிரந்தரமாக நீக்கும்',
  'and all related records. This action cannot be undone.': 'மற்றும் அனைத்து தொடர்புடைய பதிவுகளும். இந்த செயலை மீட்டெடுக்க முடியாது.',
  'Deleting...': 'நீக்குகிறது...',
  'GTPL operation completed': 'GTPL செயல்பாடு முடிந்தது',
  'GTPL operation failed': 'GTPL செயல்பாடு தோல்வியடைந்தது',
  'Failed to get status': 'நிலை பெற முடியவில்லை',
  'Customer surrendered successfully': 'வாடிக்கையாளர் வெற்றிகரமாக திருப்பி ஒப்படைக்கப்பட்டார்',
  'Surrender failed': 'திருப்பி ஒப்படைப்பு தோல்வி',
  'STB swapped successfully': 'STB வெற்றிகரமாக மாற்றப்பட்டது',
  'Swap failed': 'STB மாற்றம் தோல்வி',
  'Customer': 'வாடிக்கையாளர்',
  // Add customer
  'Create a new customer record and connection': 'புதிய வாடிக்கையாளர் பதிவு மற்றும் இணைப்பை உருவாக்கவும்',
  'Name is required': 'பெயர் கட்டாயம்',
  'Phone is required': 'தொலைபேசி கட்டாயம்',
  'Area is required': 'பகுதி கட்டாயம்',
  'STB Number is required': 'STB எண் கட்டாயம்',
  'Plan is required': 'திட்டம் கட்டாயம்',
  'Connection Fee is required': 'இணைப்பு கட்டணம் கட்டாயம்',
  'Failed to create customer. Please try again.': 'வாடிக்கையாளரை உருவாக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'Customer Created!': 'வாடிக்கையாளர் உருவாக்கப்பட்டது!',
  '{name} has been added successfully.': '{name} வெற்றிகரமாக சேர்க்கப்பட்டார்.',
  'View Customer': 'வாடிக்கையாளரை காண்க',
  'Add Another': 'மற்றொன்றை சேர்க்க',
  'Full name': 'முழு பெயர்',
  'Area / locality': 'பகுதி / வட்டாரம்',
  '(optional)': '(விருப்பம்)',
  'Door no, street': 'கதவு எண், தெரு',
  'No spare STBs in inventory for {mso}. Add STBs to inventory first.': '{mso} க்கு இருப்பில் உதிரி STB இல்லை. முதலில் இருப்பில் STB சேர்க்கவும்.',
  'Used to filter plans only': 'திட்டங்களை வடிகட்ட மட்டுமே பயன்படுகிறது',
  'Select a plan': 'திட்டத்தை தேர்வு செய்யவும்',
  'No active plans for {mso}': '{mso} க்கு செயலில் உள்ள திட்டங்கள் இல்லை',
  'Activation Date': 'செயல்படுத்தும் தேதி',
  'Connection Fee': 'இணைப்பு கட்டணம்',
  '0 (one-time new connection charge)': '0 (புதிய இணைப்புக்கான ஒரே முறை கட்டணம்)',
  'Creating...': 'உருவாக்குகிறது...',
  'Create Customer': 'வாடிக்கையாளர் உருவாக்கு',
  // Connections
  'Manage connection statuses, temp disconnects, and reconnections': 'இணைப்பு நிலைகள், தற்காலிக துண்டிப்புகள் மற்றும் மறு இணைப்புகளை நிர்வகிக்கவும்',
  'Temp Disconnected': 'தற்காலிக துண்டிப்பு',
  'Total Customers': 'மொத்த வாடிக்கையாளர்கள்',
  'Temp Disconnected Customers ({n})': 'தற்காலிக துண்டிக்கப்பட்ட வாடிக்கையாளர்கள் ({n})',
  'Search...': 'தேடு...',
  'No matching customers': 'பொருந்தும் வாடிக்கையாளர்கள் இல்லை',
  'No temp disconnected customers': 'தற்காலிக துண்டிக்கப்பட்ட வாடிக்கையாளர்கள் இல்லை',
  'Reclaimed STB': 'மீட்டெடுக்கப்பட்ட STB',
  'Reconnect': 'மீண்டும் இணைக்கவும்',
  'Reconnect Customer': 'வாடிக்கையாளரை மீண்டும் இணைக்கவும்',
  'No phone': 'தொலைபேசி இல்லை',
  'Enter STB number': 'STB எண்ணை உள்ளிடவும்',
  'Original STB: {stb} (pre-filled)': 'அசல் STB: {stb} (முன் நிரப்பப்பட்டது)',
  'Reconnecting...': 'மீண்டும் இணைக்கிறது...',
  'Reconnect failed': 'மீண்டும் இணைக்க முடியவில்லை',
  // Surrender
  'Surrender Requests': 'திருப்பி ஒப்படைப்பு கோரிக்கைகள்',
  'Manage customer surrender and reactivation requests': 'வாடிக்கையாளர் திருப்பி ஒப்படைப்பு மற்றும் மீண்டும் செயல்படுத்தும் கோரிக்கைகளை நிர்வகிக்கவும்',
  'Approved': 'ஏற்கப்பட்டது',
  'Rejected': 'நிராகரிக்கப்பட்டது',
  'Search customer...': 'வாடிக்கையாளரை தேடு...',
  'Approve': 'ஏற்க',
  'Reject': 'நிராகரி',
  'Surrender Request': 'திருப்பி ஒப்படைப்பு கோரிக்கை',
  'Review notes (optional)...': 'மதிப்பாய்வு குறிப்புகள் (விருப்பம்)...',
  'Processing...': 'செயலாக்குகிறது...',
  'Failed to review': 'மதிப்பாய்வு தோல்வி',
  'Reactivate Customer': 'வாடிக்கையாளரை மீண்டும் செயல்படுத்து',
  'Reactivate customer {id}? This will restore their connections to Active status.': 'வாடிக்கையாளர் {id} ஐ மீண்டும் செயல்படுத்தவா? இது அவர்களின் இணைப்புகளை செயலில் நிலைக்கு மீட்டெடுக்கும்.',
  'Reactivating...': 'மீண்டும் செயல்படுத்துகிறது...',
  'Reactivate': 'மீண்டும் செயல்படுத்து',
  'No surrender requests found': 'திருப்பி ஒப்படைப்பு கோரிக்கைகள் இல்லை',
  'Requested: {date}': 'கோரப்பட்டது: {date}',
  'Reviewed: {date}': 'மதிப்பாய்வு செய்யப்பட்டது: {date}',
  'Reason: {reason}': 'காரணம்: {reason}',
  'Notes: {notes}': 'குறிப்புகள்: {notes}',
  'Request reviewed': 'கோரிக்கை மதிப்பாய்வு செய்யப்பட்டது',
  'Customer reactivated': 'வாடிக்கையாளர் மீண்டும் செயல்படுத்தப்பட்டார்',
  'all': 'அனைத்தும்',
  'pending': 'நிலுவையில்',
  'approved': 'ஏற்கப்பட்டது',
  'rejected': 'நிராகரிக்கப்பட்டது',
  'ID: {id}': 'ID: {id}',
  "Deleting this payment will recompute the customer's expiry date. This cannot be undone.": 'இந்த பணம் செலுத்தலை நீக்கினால், வாடிக்கையாளரின் காலாவதி தேதி மீண்டும் கணக்கிடப்படும். இதை மீட்டெடுக்க முடியாது.',
};
export default customers;
