// dashboard translations (Dashboard, AgentDashboard, MyCollections, NotRenewed, Unpaid, Reminders)
const dashboard: Record<string, string> = {
  'Synced: {new} new, {updated} updated': 'ஒத்திசைக்கப்பட்டது: {new} புதியது, {updated} புதுப்பிக்கப்பட்டது',
  'Error: {detail}': 'பிழை: {detail}',
  'Unable to load dashboard data. Please try again.': 'டாஷ்போர்டு தரவை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'Hi {name}, your cable TV payment of ₹{amount} is pending. Please pay before 12th to avoid disconnection. Thank you - SSN Cables': 'வணக்கம் {name}, உங்கள் கேபிள் டிவி கட்டணம் ₹{amount} நிலுவையில் உள்ளது. இணைப்பு துண்டிப்பை தவிர்க்க 12ம் தேதிக்குள் செலுத்தவும். நன்றி - SSN Cables',
  'GTPL Wallet Low': 'GTPL வாலட் குறைவு',
  'Balance: ₹{bal} — renewals will fail. Recharge needed.': 'இருப்பு: ₹{bal} — புதுப்பித்தல் தோல்வியடையும். ரீசார்ஜ் தேவை.',
  'GTPL Wallet: ₹{bal}': 'GTPL வாலட்: ₹{bal}',
  '{month} Collection': '{month} வசூல்',
  'Collected': 'வசூலிக்கப்பட்டது',
  '{n} payments today': '{n} பணம் செலுத்தல்கள் இன்று',
  'Pending': 'நிலுவையில்',
  '{n} customers': '{n} வாடிக்கையாளர்கள்',
  'Today': 'இன்று',
  '{n} collected': '{n} வசூலிக்கப்பட்டது',
  'MSO Deadline': 'MSO கடைசி தேதி',
  'DUE!': 'காலாவதி!',
  'DUE': 'காலாவதி',
  'Unpaid': 'செலுத்தாதவர்கள்',
  'New This Month': 'இந்த மாதம் புதியவர்கள்',
  'Temp DC': 'தற்காலிக இணைப்பு துண்டிப்பு',
  'Yesterday': 'நேற்று',
  'Follow Up Today ({n})': 'இன்று பின்தொடர்வது ({n})',
  'Paid {m1}, not {m2}': '{m1} செலுத்தினர், {m2} இல்லை',
  'plan': 'திட்டம்',
  'View All {n}': 'அனைத்தையும் காண்க {n}',
  'Collector Leaderboard': 'வசூல் தரவரிசை',
  'total': 'மொத்தம்',
  '{n} payments': '{n} பணம் செலுத்தல்கள்',
  '↑ {n} today': '↑ {n} இன்று',
  '{pct}% of total': 'மொத்தத்தில் {pct}%',
  'Payment Modes': 'பணம் செலுத்தும் முறைகள்',
  'Cash → Digital Migration': 'பணம் → டிஜிட்டல் மாற்றம்',
  '{month} Digital': '{month} டிஜிட்டல்',
  '{a}/{b} customers': '{a}/{b} வாடிக்கையாளர்கள்',
  '💵→📱 Cash to Digital': '💵→📱 பணத்திலிருந்து டிஜிட்டல்',
  '📱→📱 Stable Digital': '📱→📱 நிலையான டிஜிட்டல்',
  '💵→💵 Stable Cash': '💵→💵 நிலையான பணம்',
  '📱→💵 Digital to Cash': '📱→💵 டிஜிட்டலிருந்து பணம்',
  '{pct}% of repeat customers': 'மீண்டும் வாடிக்கையாளர்களில் {pct}%',
  '📊 6-Month Digital Payment % Trend': '📊 6 மாத டிஜிட்டல் கட்டண % போக்கு',
  '✅ {n} customers shifted to Digital': '✅ {n} வாடிக்கையாளர்கள் டிஜிட்டலுக்கு மாறினர்',
  '⚠️ {n} went back to Cash': '⚠️ {n} பணத்திற்கு திரும்பினர்',
  'Due & Overdue ({n} customers)': 'நிலுவை & காலாவதி ({n} வாடிக்கையாளர்கள்)',
  'View All': 'அனைத்தையும் காண்க',
  'All customers have paid this month!': 'அனைத்து வாடிக்கையாளர்களும் இந்த மாதம் செலுத்திவிட்டனர்!',
  '+ {n} more unpaid customers →': '+ {n} மேலும் செலுத்தாத வாடிக்கையாளர்கள் →',
  'MSO Profitability': 'MSO லாபம்',
  'Boxes': 'பெட்டிகள்',
  'ARPU': 'ARPU',
  'Revenue': 'வருவாய்',
  'MSO Cost': 'MSO செலவு',
  'Net Profit': 'நிகர லாபம்',
  '/box MSO cost': '/பெட்டி MSO செலவு',
  'Laya Internet': 'லயா இன்டர்நெட்',
  'Sync subscribers from Laya CRM': 'லயா CRM இலிருந்து சந்தாதாரர்களை ஒத்திசைக்கவும்',
  'Syncing...': 'ஒத்திசைக்கிறது...',
  'Sync Subscribers from CRM': 'CRM இலிருந்து சந்தாதாரர்களை ஒத்திசைக்கவும்',
  '6-Month Revenue Trend': '6 மாத வருவாய் போக்கு',
  'No trend data': 'போக்கு தரவு இல்லை',
  'Overdue Aging': 'காலாவதி பகுப்பு',
  'Current': 'தற்போதைய',
  '1-2 months': '1-2 மாதங்கள்',
  '3-5 months': '3-5 மாதங்கள்',
  '6+ months': '6+ மாதங்கள்',
  'STB Inventory Health': 'STB இருப்பு நிலை',
  'Manage': 'நிர்வகி',
  'Available': 'கிடைக்கிறது',
  'Spare Stock': 'உதிரி இருப்பு',
  'Assigned': 'ஒதுக்கப்பட்டது',
  'Faulty/Repair': 'பழுது/பழுதுபார்ப்பு',
  'With MSO': 'MSO உடன்',
  'No STB inventory data': 'STB இருப்பு தரவு இல்லை',
  'Unable to load dashboard. Please try again.': 'டாஷ்போர்டை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'Agent': 'முகவர்',
  'Hi, {name} 👋': 'வணக்கம், {name} 👋',
  '{month} Target': '{month} இலக்கு',
  'This Week': 'இந்த வாரம்',
  'Last Month': 'கடந்த மாதம்',
  'previous': 'முந்தைய',
  '{n} Day Streak!': '{n} நாள் தொடர்!',
  'Keep collecting daily to maintain it 🔥': 'அதை பராமரிக்க தினமும் வசூல் செய்யுங்கள் 🔥',
  'Record Payment': 'பணம் பதிவு செய்ய',
  'No collections yet today. Start collecting!': 'இன்று இன்னும் வசூல் இல்லை. வசூல் தொடங்குங்கள்!',
  '{n} customers to follow up': '{n} வாடிக்கையாளர்கள் பின்தொடர வேண்டும்',
  'Paid last month, not renewed yet': 'கடந்த மாதம் செலுத்தினர், இன்னும் புதுப்பிக்கவில்லை',
  'View Follow-up List': 'பின்தொடர்வு பட்டியலை காண்க',
  'Your Areas': 'உங்கள் பகுதிகள்',
  '{n} unpaid': '{n} செலுத்தவில்லை',
  'pending': 'நிலுவை',
  'Open Service Requests ({n})': 'திறந்த சேவை கோரிக்கைகள் ({n})',
  'Tap to view and resolve': 'பார்க்கவும் தீர்க்கவும் தட்டவும்',
  'My Collections': 'என் வசூல்',
  'Your personal collection summary and history': 'உங்கள் தனிப்பட்ட வசூல் சுருக்கம் மற்றும் வரலாறு',
  'Total Collected': 'மொத்த வசூல்',
  'Payments Made': 'செய்யப்பட்ட பணம் செலுத்தல்கள்',
  'Avg per Payment': 'ஒவ்வொரு பணத்தின் சராசரி',
  'From': 'இருந்து',
  'To': 'வரை',
  'Clear': 'அழி',
  'Export CSV': 'CSV ஏற்றுமதி',
  'No collections found. Payments you collect will appear here.': 'வசூல் எதுவும் இல்லை. நீங்கள் வசூலிக்கும் பணம் இங்கே தோன்றும்.',
  'Customer': 'வாடிக்கையாளர்',
  'Area': 'பகுதி',
  'Amount': 'தொகை',
  'Mode': 'முறை',
  'Source': 'மூலம்',
  'Date': 'தேதி',
  'Previous': 'முந்தைய',
  'Page {p} of {t}': 'பக்கம் {p} / {t}',
  'Next': 'அடுத்து',
  'Not Renewed': 'புதுப்பிக்காதவர்கள்',
  'Lost Revenue': 'இழந்த வருவாய்',
  'Search by name, phone, or STB...': 'பெயர், தொலைபேசி அல்லது STB மூலம் தேடு...',
  'Failed to load not-renewed list': 'புதுப்பிக்காதவர்கள் பட்டியலை ஏற்ற முடியவில்லை',
  'No matching customers': 'பொருந்தும் வாடிக்கையாளர்கள் இல்லை',
  'No customers in this list': 'இந்த பட்டியலில் வாடிக்கையாளர்கள் இல்லை',
  'Name': 'பெயர்',
  'Phone': 'தொலைபேசி',
  'STB': 'STB',
  'Plan': 'திட்டம்',
  'Expiry': 'காலாவதி',
  'January': 'ஜனவரி',
  'February': 'பிப்ரவரி',
  'March': 'மார்ச்',
  'April': 'ஏப்ரல்',
  'May': 'மே',
  'June': 'ஜூன்',
  'July': 'ஜூலை',
  'August': 'ஆகஸ்ட்',
  'September': 'செப்டம்பர்',
  'October': 'அக்டோபர்',
  'November': 'நவம்பர்',
  'December': 'டிசம்பர்',
  'Unpaid Customers': 'செலுத்தாத வாடிக்கையாளர்கள்',
  'Customers with expired subscriptions as of {date}': '{date} நிலவரப்படி காலாவதியான சந்தாக்கள் உள்ள வாடிக்கையாளர்கள்',
  'Total Unpaid': 'மொத்தம் செலுத்தாதவர்கள்',
  'Pending Amount': 'நிலுவை தொகை',
  '2 Months Ago': '2 மாதங்களுக்கு முன்பு',
  '3 Months Ago': '3 மாதங்களுக்கு முன்பு',
  'All Areas': 'அனைத்து பகுதிகள்',
  'Failed to load unpaid customers': 'செலுத்தாத வாடிக்கையாளர்களை ஏற்ற முடியவில்லை',
  'No unpaid customers found': 'செலுத்தாத வாடிக்கையாளர்கள் இல்லை',
  'Gap': 'இடைவெளி',
  'Page {p} of {t} ({n} customers)': 'பக்கம் {p} / {t} ({n} வாடிக்கையாளர்கள்)',
  'Prev': 'முந்தைய',
  'Reminders': 'நினைவூட்டல்கள்',
  'Send WhatsApp renewal reminders to customers with overdue subscriptions': 'காலாவதியான சந்தாக்கள் உள்ள வாடிக்கையாளர்களுக்கு WhatsApp புதுப்பித்தல் நினைவூட்டல்களை அனுப்பவும்',
  'Sent Today': 'இன்று அனுப்பப்பட்டவை',
  'Total Sent': 'மொத்தம் அனுப்பப்பட்டவை',
  'WhatsApp': 'வாட்ஸ்அப்',
  'Connected': 'இணைக்கப்பட்டது',
  'Offline': 'ஆஃப்லைன்',
  'Sent {n} reminder(s)': '{n} நினைவூட்டல்கள் அனுப்பப்பட்டன',
  '{n} failed': '{n} தோல்வி',
  'Select None': 'எதுவும் தேர்ந்தெடுக்க வேண்டாம்',
  'Select All': 'அனைத்தையும் தேர்ந்தெடு',
  'Custom Message': 'தனிப்பயன் செய்தி',
  'Optional custom reminder text (leave blank for default)': 'விருப்ப தனிப்பயன் நினைவூட்டல் உரை (இயல்புநிலைக்கு காலியாக விடவும்)',
  '{n} selected': '{n} தேர்ந்தெடுக்கப்பட்டது',
  'Send Reminders ({n})': 'நினைவூட்டல்களை அனுப்பு ({n})',
  'No reminders due': 'நினைவூட்டல்கள் நிலுவையில் இல்லை',
  'Months Due': 'நிலுவை மாதங்கள்',
  'Reminder History': 'நினைவூட்டல் வரலாறு',
  'No reminders sent yet': 'இன்னும் நினைவூட்டல்கள் அனுப்பப்படவில்லை',
  '{n} reminder(s) sent': '{n} நினைவூட்டல்கள் அனுப்பப்பட்டன',
  'by {name}': '{name} ஆல்',
  'Send Reminders?': 'நினைவூட்டல்களை அனுப்பவா?',
  'This will send WhatsApp renewal reminders to {n} customer(s).': 'இது {n} வாடிக்கையாளருக்கு WhatsApp புதுப்பித்தல் நினைவூட்டல்களை அனுப்பும்.',
  'Custom message:': 'தனிப்பயன் செய்தி:',
  'Sending...': 'அனுப்புகிறது...',
  'Send': 'அனுப்பு',
  "Today's Collections": 'இன்றைய வசூல்',
  '{n} customers shifted to Digital': '{n} வாடிக்கையாளர்கள் டிஜிட்டலுக்கு மாறியுள்ளனர்',
  '{n} went back to Cash': '{n} பேர் ரொக்கம் முறைக்குத் திரும்பினர்',
  "Customers who haven't renewed for {month}": '{month} மாதத்திற்கு புதுப்பிக்காத வாடிக்கையாளர்கள்',
  "These customers paid last month but haven't renewed. Call or WhatsApp them first.": 'இந்த வாடிக்கையாளர்கள் கடந்த மாதம் செலுத்தியுள்ளனர், ஆனால் புதுப்பிக்கவில்லை. முதலில் அழைக்கவும் அல்லது WhatsApp செய்யவும்.',
};
export default dashboard;
