// Layout / nav translations (admin app)
export default {
  'Dashboard': 'டாஷ்போர்டு',
  'Reports': 'அறிக்கைகள்',
  'Customers': 'வாடிக்கையாளர்கள்',
  'Payments': 'பணம் செலுத்தல்கள்',
  'Plans': 'திட்டங்கள்',
  'Connections': 'இணைப்புகள்',
  'Service Requests': 'சேவை கோரிக்கைகள்',
  'Settings': 'அமைப்புகள்',
  'Operators': 'ஆபரேட்டர்கள்',
  'Employees': 'பணியாளர்கள்',
  'Add Customer': 'வாடிக்கையாளர் சேர்க்க',
  'Not Renewed': 'புதுப்பிக்காதவர்கள்',
  'Reminders': 'நினைவூட்டல்கள்',
  'Audit Log': 'தணிக்கை பதிவு',
  'Surrender': 'திருப்பி ஒப்படைப்பு',
  'Inventory': 'இருப்பு',
  'My Collections': 'என் வசூல்',
  'Map': 'வரைபடம்',
  'Online Payments': 'ஆன்லைன் பணம்',
  'Unpaid': 'செலுத்தாதவர்கள்',
  'Logout': 'வெளியேறு',
  'Login': 'உள்நுழை',
  'Cable TV Management': 'கேபிள் டிவி மேலாண்மை',
  'Hard refresh — clears cache & loads latest version': 'புதுப்பிப்பு — கேச் அழித்து சமீபத்திய பதிப்பை ஏற்றும்',
  'Prabhu': 'பிரபு',
  'Admin': 'நிர்வாகி',
  'Master': 'மாஸ்டர்',
  'Agent': 'முகவர்',
  'Collection Agent': 'வசூல் முகவர்',
  'Support': 'ஆதரவு',
  'Collection Point': 'வசூல் மையம்',
  'Install Wasool App': 'Wasool ஆப்பை நிறுவு',
} as Record<string, string>;
