// Map view translations
export default {
  'PAID': 'செலுத்தப்பட்டது',
  'NOT RENEWED (paid last month)': 'புதுப்பிக்கப்படவில்லை (கடந்த மாதம் செலுத்தினார்)',
  'OVERDUE (2+ months)': 'தாமதம் (2+ மாதங்கள்)',
  'e.g. 1st floor': 'எ.கா. 1வது மாடி',
  'save': 'சேமி',
  'cancel': 'ரத்து',
  'No floor/unit set': 'மாடி/அலகு அமைக்கப்படவில்லை',
  'edit': 'திருத்து',
  'Plan': 'திட்டம்',
  'Reminded {n}× this month': 'இந்த மாதம் {n} முறை நினைவூட்டப்பட்டது',
  ' · last by {name}': ' · கடைசியாக {name} மூலம்',
  'Navigate': 'வழிகாட்டி',
  'Remind': 'நினைவூட்டு',
  'Record payment': 'பணம் பதிவு செய்',
  'Monthly reminder': 'மாதாந்திர நினைவூட்டல்',
  'Reconnection reminder': 'மறு இணைப்பு நினைவூட்டல்',
  'Could not save — that point may be outside your collection area.': 'சேமிக்க முடியவில்லை — அந்த புள்ளி உங்கள் வசூல் பகுதிக்கு வெளியே இருக்கலாம்.',
  'Could not save the floor/unit.': 'மாடி/அலகை சேமிக்க முடியவில்லை.',
  'That point is outside your collection area, so it was not saved.': 'அந்த புள்ளி உங்கள் வசூல் பகுதிக்கு வெளியே உள்ளது, எனவே சேமிக்கப்படவில்லை.',
  'This device has no GPS/location support.': 'இந்த சாதனத்தில் GPS/இருப்பிட ஆதரவு இல்லை.',
  'Your current location is about {km} km from your collection area, so it was not saved. Use GPS only while standing at the customer\'s house, or place the pin on the map.': 'உங்கள் தற்போதைய இருப்பிடம் உங்கள் வசூல் பகுதியிலிருந்து சுமார் {km} கிமீ தொலைவில் உள்ளது, எனவே சேமிக்கப்படவில்லை. வாடிக்கையாளரின் வீட்டில் நிற்கும்போது மட்டுமே GPS பயன்படுத்தவும், அல்லது வரைபடத்தில் பின்னை வைக்கவும்.',
  'Could not get GPS: ': 'GPS பெற முடியவில்லை: ',
  'Voice search needs a supported browser like Chrome or Edge (or Chrome on Android).': 'குரல் தேடலுக்கு Chrome அல்லது Edge போன்ற ஆதரிக்கப்படும் உலாவி தேவை (அல்லது Android இல் Chrome).',
  'Could not get your location: ': 'உங்கள் இருப்பிடத்தை பெற முடியவில்லை: ',
  'Remove {name}\'s location? They\'ll go back to "without location".': '{name} இன் இடத்தை நீக்கவா? அவர்கள் "இடம் இல்லாமல்" பட்டியலுக்கு செல்வார்கள்.',
  'Collection Map': 'வசூல் வரைபடம்',
  'Placed {n}/{total}': 'இடம் குறிக்கப்பட்டது {n}/{total}',
  '{n} paid': '{n} செலுத்தினர்',
  '{n} not renewed': '{n} புதுப்பிக்கவில்லை',
  '{n} overdue': '{n} தாமதம்',
  '(placed, this month)': '(இந்த மாதம் இடம் குறிக்கப்பட்டவை)',
  'Not renewed': 'புதுப்பிக்கப்படவில்லை',
  'Overdue': 'தாமதம்',
  'Show my current location on the map': 'வரைபடத்தில் எனது தற்போதைய இருப்பிடத்தை காட்டு',
  'Stop': 'நிறுத்து',
  'My location': 'என் இருப்பிடம்',
  'You are about {km} km outside your collection area.': 'உங்கள் வசூல் பகுதிக்கு வெளியே சுமார் {km} கிமீ இருக்கிறீர்கள்.',
  'You are inside your collection area.': 'நீங்கள் உங்கள் வசூல் பகுதிக்குள் இருக்கிறீர்கள்.',
  'Tap {name}\'s home on the map to {action} the pin.': 'வரைபடத்தில் {name} வீட்டை {action} தட்டவும்.',
  'move': 'நகர்த்த',
  'set': 'வைக்க',
  'or use my GPS': 'அல்லது எனது GPS ஐ பயன்படுத்தவும்',
  'Use my current GPS instead': 'அதற்கு பதிலாக எனது தற்போதைய GPS ஐ பயன்படுத்தவும்',
  'Move location': 'இடத்தை நகர்த்து',
  '{n} connections here': 'இங்கே {n} இணைப்புகள்',
  'You are here': 'நீங்கள் இங்கே இருக்கிறீர்கள்',
  'Outside your collection area': 'உங்கள் வசூல் பகுதிக்கு வெளியே',
  'Without location': 'இடம் இல்லாமல்',
  'With location': 'இடத்துடன்',
  'Listening…': 'கேட்கிறது…',
  'Search name, phone or ID': 'பெயர், தொலைபேசி அல்லது ID தேடு',
  'Voice search — tap and say the customer name': 'குரல் தேடல் — தட்டி வாடிக்கையாளர் பெயரை சொல்லுங்கள்',
  'No customers here.': 'இங்கே வாடிக்கையாளர்கள் இல்லை.',
  'No location': 'இடம் இல்லை',
  'This pin is outside your collection area': 'இந்த பின் உங்கள் வசூல் பகுதிக்கு வெளியே உள்ளது',
  'outside area': 'பகுதிக்கு வெளியே',
  'Show on map': 'வரைபடத்தில் காட்டு',
  'show': 'காட்டு',
  'Tap the map to move this pin': 'இந்த பின்னை நகர்த்த வரைபடத்தில் தட்டவும்',
  'Remove this location': 'இந்த இடத்தை நீக்கு',
  'clear': 'அழி',
  'Tap the map to place this customer': 'இந்த வாடிக்கையாளரை வைக்க வரைபடத்தில் தட்டவும்',
  'place': 'வை',
  'Use my current GPS': 'எனது தற்போதைய GPS ஐ பயன்படுத்தவும்',
  // WhatsApp reminder templates (sent to customers)
  'STB No: {stb}  |  Mobile: your registered number': 'STB எண்: {stb}  |  மொபைல்: உங்கள் பதிவு செய்த எண்',
  'STB number + your registered mobile number': 'STB எண் + உங்கள் பதிவு செய்த மொபைல் எண்',
  'Or recharge yourself online:\nLogin: {link}\n{cred}\n\n': 'அல்லது நீங்களே ஆன்லைனில் ரீசார்ஜ் செய்யுங்கள்:\nஉள்நுழைவு: {link}\n{cred}\n\n',
  'Dear Customer, your cable TV subscription for {month} is due. Kindly pay before the 12th to avoid disconnection.\n\nPay now (GPay/PhonePe): {link}\nUPI: {upi}\n\n{recharge}Thank you.\n- {business}': 'அன்புள்ள வாடிக்கையாளரே, {month} மாத கேபிள் டிவி சந்தா கட்டணம் செலுத்த வேண்டும். துண்டிப்பு ஏற்படாமல் இருக்க 12ஆம் தேதிக்குள் தயவுசெய்து செலுத்தவும்.\n\nஇப்போது செலுத்துங்கள் (GPay/PhonePe): {link}\nUPI: {upi}\n\n{recharge}நன்றி.\n- {business}',
  'Dear Customer, your cable TV connection is disconnected due to non-payment.\n\nAmount to reconnect: ₹{amount} (as on {date})\n\nPay now (GPay/PhonePe): {link}\nUPI: {upi}\n\n{recharge}- {business}': 'அன்புள்ள வாடிக்கையாளரே, கட்டணம் செலுத்தாததால் உங்கள் கேபிள் டிவி இணைப்பு துண்டிக்கப்பட்டுள்ளது.\n\nமீண்டும் இணைக்க வேண்டிய தொகை: ₹{amount} ({date} நிலவரப்படி)\n\nஇப்போது செலுத்துங்கள் (GPay/PhonePe): {link}\nUPI: {upi}\n\n{recharge}- {business}',
  'If this keeps happening, the map_note database column may be missing — run migrate_customer_map_note.py on the server.': 'இது தொடர்ந்து நடந்தால், map_note தரவுத்தள நெடுவரிசை இல்லாமல் இருக்கலாம் — சர்வரில் migrate_customer_map_note.py ஐ இயக்கவும்.',
} as Record<string, string>;
