// payments translations (Payments, RecordPayment, OnlinePayments pages)
const payments: Record<string, string> = {
  // Payments list
  'Record Payment': 'பணம் பதிவு செய்',
  '{n} payments this period': 'இந்த காலகட்டத்தில் {n} பணம் செலுத்தல்கள்',
  'collected': 'வசூலிக்கப்பட்டது',
  'From': 'முதல்',
  'To': 'வரை',
  'Search customer or reference...': 'வாடிக்கையாளர் அல்லது குறிப்பு எண்ணில் தேடு...',
  'No payments in this period': 'இந்த காலகட்டத்தில் பணம் செலுத்தல்கள் இல்லை',
  'Mode': 'முறை',
  'Action': 'செயல்',
  'Delete payment': 'பணம் நீக்கு',
  'Delete Payment?': 'பணம் நீக்கவா?',
  'Deleting this payment will recompute the customer\'s expiry date. This cannot be undone.': 'இந்த பணத்தை நீக்கினால் வாடிக்கையாளரின் காலாவதி தேதி மீண்டும் கணக்கிடப்படும். இதை மீட்டெடுக்க முடியாது.',
  'Payment deleted': 'பணம் நீக்கப்பட்டது',
  'Add Payment': 'பணம் சேர்க்க',
  // Record payment
  'Search customer by name or phone...': 'பெயர் அல்லது தொலைபேசியில் வாடிக்கையாளரை தேடு...',
  'Change': 'மாற்று',
  'Due by {day}th': '{day}ஆம் தேதிக்குள் செலுத்தவும்',
  'No customers found matching "{query}"': '"{query}" உடன் பொருந்தும் வாடிக்கையாளர்கள் இல்லை',
  'View customer profile': 'வாடிக்கையாளர் சுயவிவரத்தை காண்க',
  'ID: {id} · Tap to view profile': 'ID: {id} · சுயவிவரம் பார்க்க தட்டவும்',
  'STB No': 'STB எண்',
  'Package': 'தொகுப்பு',
  'Expiry': 'காலாவதி',
  'Connection (STB)': 'இணைப்பு (STB)',
  'Connection {id}': 'இணைப்பு {id}',
  'Select plan': 'திட்டத்தை தேர்வு செய்யவும்',
  'Billing Month': 'பில்லிங் மாதம்',
  '{n} (1 free!)': '{n} (1 இலவசம்!)',
  'Full Amount': 'முழு தொகை',
  'Prorata Discount': 'ப்ரோராட்டா தள்ளுபடி',
  'Discount ({reason})': 'தள்ளுபடி ({reason})',
  'Amount to Pay': 'செலுத்த வேண்டிய தொகை',
  'Discount': 'தள்ளுபடி',
  'Reason': 'காரணம்',
  'Select reason': 'காரணத்தை தேர்வு செய்யவும்',
  'Any additional notes...': 'கூடுதல் குறிப்புகள் இருந்தால்...',
  'Pay ₹{amount}': 'செலுத்து ₹{amount}',
  'Pay': 'செலுத்து',
  'Payment recorded': 'பணம் பதிவு செய்யப்பட்டது',
  'For': 'எதற்கு',
  '{n} mo': '{n} மாதம்',
  'Send receipt on WhatsApp': 'வாட்ஸ்அப்பில் ரசீது அனுப்பு',
  'New payment': 'புதிய பணம்',
  'Please select a customer': 'வாடிக்கையாளரை தேர்வு செய்யவும்',
  'Please select a plan': 'திட்டத்தை தேர்வு செய்யவும்',
  'Invalid amount': 'தொகை தவறானது',
  'Please select a reason for the discount': 'தள்ளுபடிக்கான காரணத்தை தேர்வு செய்யவும்',
  'Discount cannot exceed total amount': 'தள்ளுபடி மொத்த தொகையை விட அதிகமாக இருக்க முடியாது',
  'Failed to record payment. Please try again.': 'பணம் பதிவு செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'Confirm Payment': 'பணம் உறுதிப்படுத்து',
  'Please verify before proceeding': 'தொடர்வதற்கு முன் சரிபார்க்கவும்',
  'Customer ID': 'வாடிக்கையாளர் ID',
  'Confirm & Pay': 'உறுதிப்படுத்தி செலுத்து',
  'Active | Paid': 'செயலில் | செலுத்தப்பட்டது',
  'Inactive | Unpaid': 'செயலற்றது | செலுத்தப்படவில்லை',
  'Active | Unpaid': 'செயலில் | செலுத்தப்படவில்லை',
  'Last paid till {expStr} ({n} month gap). Reconnecting — 1 month prorata.': 'கடைசியாக {expStr} வரை செலுத்தப்பட்டது ({n} மாத இடைவெளி). மீண்டும் இணைக்கிறது — 1 மாத ப்ரோராட்டா.',
  'Already paid till {expStr}. Month set to {nextMonthName} (next unpaid).': 'ஏற்கனவே {expStr} வரை செலுத்தப்பட்டது. மாதம் {nextMonthName} (அடுத்த நிலுவை) ஆக அமைக்கப்பட்டது.',
  'Cash': 'பணம்',
  'GPay': 'GPay',
  'PhonePe': 'PhonePe',
  'UPI': 'UPI',
  'Bank Transfer': 'வங்கி பரிமாற்றம்',
  'Cheque': 'காசோலை',
  'Node': 'நோட்',
  'Injector': 'இன்ஜெக்டர்',
  'Others': 'மற்றவை',
  // Online payments
  'Recorded': 'பதிவு செய்யப்பட்டது',
  'Needs review': 'மதிப்பாய்வு தேவை',
  'Unattributed': 'வாடிக்கையாளர் பொருத்தம் இல்லை',
  'Captured': 'பணம் பெறப்பட்டது',
  'Payments received automatically through the Razorpay pay page.': 'ரேஸர்பே பே பக்கத்தின் மூலம் தானாக பெறப்படும் பணம் செலுத்தல்கள்.',
  'Refresh': 'புதுப்பி',
  'Could not load online payments. You may not have permission, or the server is unavailable.': 'ஆன்லைன் பணம் செலுத்தல்களை ஏற்ற முடியவில்லை. உங்களுக்கு அனுமதி இல்லாமல் இருக்கலாம், அல்லது சேவையகம் கிடைக்கவில்லை.',
  'No online payments yet': 'இன்னும் ஆன்லைன் பணம் செலுத்தல்கள் இல்லை',
  'When a customer pays through the Razorpay pay page and the webhook fires, it will appear here.': 'வாடிக்கையாளர் ரேஸர்பே பே பக்கத்தில் செலுத்தி வெப்ஹூக் செயல்பட்டால், அது இங்கே தோன்றும்.',
  'If you made a test payment and nothing shows, the webhook likely isn\'t configured yet': 'சோதனை பணம் செலுத்தியும் எதுவும் தோன்றவில்லை என்றால், வெப்ஹூக் இன்னும் அமைக்கப்படவில்லை என்பது அர்த்தம்',
  '(Razorpay Dashboard → Settings → Webhooks →': '(ரேஸர்பே டாஷ்போர்டு → அமைப்புகள் → வெப்ஹூக்குகள் →',
  ', event': ', நிகழ்வு',
  'Unknown customer': 'தெரியாத வாடிக்கையாளர்',
  'Razorpay Dashboard → Settings → Webhooks →': 'Razorpay டாஷ்போர்டு → அமைப்புகள் → Webhooks →',
  // WhatsApp receipt message (RecordPayment success)
  'Customer: {name} ({id})': 'வாடிக்கையாளர்: {name} ({id})',
  'Amount paid: ₹{amount}': 'செலுத்திய தொகை: ₹{amount}',
  'For: {month}': 'எதற்கு: {month}',
  ' ({n} months)': ' ({n} மாதங்கள்)',
  'Thank you for your payment.': 'உங்கள் பணத்திற்கு நன்றி.',
  'UPI for next time: {upi}': 'அடுத்த முறைக்கான UPI: {upi}',
  'Valid till: {d}': 'செல்லுபடி: {d}',
  'Valid till': 'செல்லுபடி',
  'GPay / PhonePe: {num}': 'GPay / PhonePe: {num}',
  'Regards, {business}': 'நன்றி, {business}',
};
export default payments;
