// Customer portal translations (customer-facing — highest value)
export default {
  'Home': 'முகப்பு',
  'History': 'வரலாறு',
  'Support': 'உதவி',
  'Logout': 'வெளியேறு',
  'Login': 'உள்நுழை',
  'Customer Portal': 'வாடிக்கையாளர் போர்டல்',
  'Enter your STB number': 'உங்கள் STB எண்ணை உள்ளிடவும்',
  'Enter your mobile number': 'உங்கள் மொபைல் எண்ணை உள்ளிடவும்',
  'STB Number': 'STB எண்',
  'Mobile Number': 'மொபைல் எண்',
  'Verify': 'சரிபார்',
  'Invalid STB or mobile number': 'தவறான STB அல்லது மொபைல் எண்',
  'Verifying…': 'சரிபார்க்கிறது…',
  'Your Plan': 'உங்கள் திட்டம்',
  'Plan Amount': 'திட்டத் தொகை',
  'Due Date': 'நிலுவை தேதி',
  'Status': 'நிலை',
  'Active': 'செயலில்',
  'Disconnected': 'இணைப்பு துண்டிக்கப்பட்டது',
  'Pending': 'நிலுவையில்',
  'Payment History': 'பணம் செலுத்திய வரலாறு',
  'No payments yet': 'இன்னும் பணம் செலுத்தவில்லை',
  'Paid': 'செலுத்தப்பட்டது',
  'Payment Date': 'செலுத்திய தேதி',
  'Amount Paid': 'செலுத்திய தொகை',
  'Pay Now': 'இப்போது செலுத்து',
  'Pay Online': 'ஆன்லைனில் செலுத்து',
  'Recharge': 'ரீசார்ஜ்',
  'Raise a Request': 'கோரிக்கை பதிவு செய்ய',
  'Submit': 'சமர்ப்பிக்கவும்',
  'Your Request Submitted': 'உங்கள் கோரிக்கை சமர்ப்பிக்கப்பட்டது',
  'Request Type': 'கோரிக்கை வகை',
  'Describe your issue': 'உங்கள் பிரச்சனையை விவரிக்கவும்',
  'No connection issues? Request here': 'இணைப்பு பிரச்சனையா? இங்கே கோரிக்கை பதிவு செய்யவும்',
  'Thank you! Our team will contact you soon.': 'நன்றி! எங்கள் குழு விரைவில் உங்களை தொடர்பு கொள்ளும்.',
  'Back to Home': 'முகப்புக்கு திரும்பு',
  'Cable TV': 'கேபிள் டிவி',
  'Internet': 'இன்டர்நெட்',
  'Reconnection': 'மறு இணைப்பு',
  'New Connection': 'புதிய இணைப்பு',
  'Billing Issue': 'பில்லிங் பிரச்சனை',
  'Signal Issue': 'சிக்னல் பிரச்சனை',
  'Other': 'மற்றவை',
  'Submit Request': 'கோரிக்கையை சமர்ப்பிக்கவும்',
  'Welcome': 'வரவேற்கிறோம்',
  'Your account': 'உங்கள் கணக்கு',
  'Due': 'நிலுவை',
  'Last Payment': 'கடைசி பணம்',
} as Record<string, string>;
