// reports translations
const reports: Record<string, string> = {
  'Failed to delete payment. Please try again.': 'பணம் செலுத்தலை நீக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'No transactions to export': 'ஏற்றுமதி செய்ய பரிவர்த்தனைகள் இல்லை',
  'Failed to export. Please try again.': 'ஏற்றுமதி செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'No unpaid customers to export': 'ஏற்றுமதி செய்ய செலுத்தாத வாடிக்கையாளர்கள் இல்லை',
  'Reports': 'அறிக்கைகள்',
  'Paid transactions and Unpaid customers': 'செலுத்திய பரிவர்த்தனைகள் மற்றும் செலுத்தாத வாடிக்கையாளர்கள்',
  'Paid': 'செலுத்தியவர்கள்',
  'Unpaid': 'செலுத்தாதவர்கள்',
  'Transactions': 'பரிவர்த்தனைகள்',
  'Total Collected': 'மொத்த வசூல்',
  'Avg Amount': 'சராசரி தொகை',
  'to': 'வரை',
  'This Month': 'இந்த மாதம்',
  'Last Month': 'கடந்த மாதம்',
  'All Employees': 'அனைத்து பணியாளர்கள்',
  'Search name, ID, STB...': 'பெயர், ஐடி, STB மூலம் தேடு...',
  'Exporting...': 'ஏற்றுமதி செய்கிறது...',
  'No transactions in this period': 'இந்த காலகட்டத்தில் பரிவர்த்தனைகள் இல்லை',
  'Delete transaction': 'பரிவர்த்தனையை நீக்கு',
  'Collected by {name}': '{name} ஆல் வசூலிக்கப்பட்டது',
  'Search...': 'தேடு...',
  'No unpaid customers found': 'செலுத்தாத வாடிக்கையாளர்கள் இல்லை',
  'Transaction Deleted': 'பரிவர்த்தனை நீக்கப்பட்டது',
  'Expiry date updated automatically:': 'காலாவதி தேதி தானாக புதுப்பிக்கப்பட்டது:',
  'Expired (no payments left)': 'காலாவதியானது (பணம் செலுத்தல்கள் இல்லை)',
  'Done': 'முடிந்தது',
  'Delete Transaction?': 'பரிவர்த்தனையை நீக்கவா?',
  'Customer': 'வாடிக்கையாளர்',
  'Amount': 'தொகை',
  'Date': 'தேதி',
  'Mode': 'முறை',
  'Reason (optional)': 'காரணம் (விருப்பம்)',
  'e.g. Duplicate entry, wrong amount...': 'எ.கா. நகல் பதிவு, தவறான தொகை...',
  'Cancel': 'ரத்து',
  'Deleting...': 'நீக்குகிறது...',
  'Delete': 'நீக்கு',
  'Previous': 'முந்தைய',
  'Page {p} of {t} ({n} total)': 'பக்கம் {p} / {t} ({n} மொத்தம்)',
  'Next': 'அடுத்து',
  'Unpaid Customers': 'செலுத்தாத வாடிக்கையாளர்கள்',
  'Pending Amount': 'நிலுவை தொகை',
  "The customer's expiry date will be recalculated based on remaining payments.": 'வாடிக்கையாளரின் காலாவதி தேதி, மீதமுள்ள பணம் செலுத்தல்களின் அடிப்படையில் மீண்டும் கணக்கிடப்படும்.',
};
export default reports;
