// Settings / admin pages translations (Settings, AppSettings, Operators, Employees,
// AuditLog, ServiceRequests, Plans, Inventory, NotificationBell, StbCopy, Layout nav)
const settings: Record<string, string> = {
  // ── Settings page (notifications + telegram) ──
  'Configure notifications and Telegram bot': 'அறிவிப்புகள் மற்றும் டெலிகிராம் போட்டை அமைக்கவும்',
  'Notifications': 'அறிவிப்புகள்',
  'Control when payment alerts are sent to Telegram': 'பணம் செலுத்தல் எச்சரிக்கைகள் எப்போது டெலிகிராமுக்கு அனுப்பப்படும் என்பதை கட்டுப்படுத்தவும்',
  'Enable Notifications': 'அறிவிப்புகளை இயக்கு',
  'Master toggle for all alerts': 'அனைத்து எச்சரிக்கைகளுக்கும் முதன்மை சுவிட்ச்',
  'Payment Alerts': 'பணம் செலுத்தல் எச்சரிக்கைகள்',
  'Which payments trigger a notification': 'எந்த பணம் செலுத்தல்கள் அறிவிப்பை தூண்டும்',
  'All payments': 'அனைத்து பணம் செலுத்தல்கள்',
  'Disconnected customers only': 'இணைப்பு துண்டிக்கப்பட்ட வாடிக்கையாளர்கள் மட்டும்',
  'Service Alerts': 'சேவை எச்சரிக்கைகள்',
  'Which service requests trigger notifications': 'எந்த சேவை கோரிக்கைகள் அறிவிப்புகளை தூண்டும்',
  'All tickets': 'அனைத்து டிக்கெட்டுகள்',
  'High priority only': 'அதிக முன்னுரிமை மட்டும்',
  'Payment Cutoff Date': 'பணம் செலுத்தல் கட்-ஆஃப் தேதி',
  'Day of month after which unpaid connections are disconnected': 'எந்த மாத தேதிக்கு பிறகு செலுத்தாத இணைப்புகள் துண்டிக்கப்படும்',
  'Saved': 'சேமிக்கப்பட்டது',
  '1-28 only': '1-28 மட்டும்',
  'Telegram Bot': 'டெலிகிராம் போட்',
  'Link a Telegram bot to receive payment and service alerts': 'பணம் மற்றும் சேவை எச்சரிக்கைகளை பெற டெலிகிராம் போட்டை இணைக்கவும்',
  'Linked ({n} users)': 'இணைக்கப்பட்டது ({n} பயனர்கள்)',
  'Not linked': 'இணைக்கப்படவில்லை',
  'Detect Users': 'பயனர்களை கண்டறி',
  'Unlink Bot': 'போட்டை துண்டி',
  'Unlink Telegram bot? You will stop receiving alerts.': 'டெலிகிராம் போட்டை துண்டிக்கவா? எச்சரிக்கைகள் வருவது நிறுத்தப்படும்.',
  'Bot Token (from @BotFather)': 'போட் டோக்கன் (@BotFather இலிருந்து)',
  'Chat IDs (optional — leave blank to auto-detect)': 'சாட் ஐடிகள் (விருப்பம் — காலியாக விட்டால் தானாக கண்டறியும்)',
  'To auto-detect: send /start to your bot first, then click Verify': 'தானாக கண்டறிய: முதலில் உங்கள் போட்டிற்கு /start அனுப்பவும், பிறகு சரிபார் என்பதை கிளிக் செய்யவும்',
  'Verifying...': 'சரிபார்க்கிறது...',
  'Verify & Link': 'சரிபார்த்து இணைக்கவும்',
  'Settings updated': 'அமைப்புகள் புதுப்பிக்கப்பட்டது',
  'Update failed': 'புதுப்பிப்பு தோல்வி',
  'Telegram bot linked': 'டெலிகிராம் போட் இணைக்கப்பட்டது',
  'Verification failed': 'சரிபார்ப்பு தோல்வி',
  'Detected {n} users': 'கண்டறியப்பட்ட பயனர்கள்: {n}',
  'Detection failed': 'கண்டறிதல் தோல்வி',
  'Telegram bot unlinked': 'டெலிகிராம் போட் துண்டிக்கப்பட்டது',
  'Laya Internet': 'லயா இன்டர்நெட்',
  'Sync subscribers from Laya CRM and import monthly statements for auto-reconciliation.': 'லயா CRM இலிருந்து சந்தாதாரர்களை ஒத்திசைத்து, தானியங்கி சரிசெய்தலுக்கு மாத அறிக்கைகளை இறக்குமதி செய்யவும்.',
  'Syncing...': 'ஒத்திசைக்கிறது...',
  'Sync Subscribers': 'சந்தாதாரர்களை ஒத்திசை',
  'Importing...': 'இறக்குமதி செய்கிறது...',
  'Import Statement': 'அறிக்கையை இறக்குமதி செய்',

  // ── Branding / white-label ──
  'Branding / White-label': 'பிராண்டிங் / ஒயிட்-லேபிள்',
  'These appear on the public website, customer portal, staff panels, and WhatsApp messages.': 'இவை பொது இணையதளம், வாடிக்கையாளர் போர்டல், ஊழியர் பேனல்கள் மற்றும் வாட்ஸ்அப் செய்திகளில் தோன்றும்.',
  'Prorata billing': 'பிரோராட்டா பில்லிங்',
  'ON = partial-month charges on reconnection & late-month payments (SSN style).': 'ஆன் = மறு இணைப்பு மற்றும் மாத இறுதி பணம் செலுத்தல்களில் பகுதி மாத கட்டணம் (SSN பாணி).',
  'OFF = always charge full month(s), no day-based splits.': 'ஆஃப் = எப்போதும் முழு மாத கட்டணம், நாள் அடிப்படையிலான பிரிவு இல்லை.',
  'Toggle prorata': 'பிரோராட்டாவை மாற்று',
  'Billing cycle day': 'பில்லிங் சுழற்சி நாள்',
  'Reconnect prorata counts days till this − 1. Default 13 (cycle 13th–12th).': 'மறு இணைப்பு பிரோராட்டா இந்த நாளுக்கு − 1 வரை கணக்கிடும். இயல்புநிலை 13 (சுழற்சி 13 முதல் 12 வரை).',
  'Prorata-until day': 'பிரோராட்டா வரையிலான நாள்',
  'Late-month payments charge till this day of next month. Default 16.': 'மாத இறுதி பணம் செலுத்தல்கள் அடுத்த மாதம் இந்த நாள் வரை கட்டணம். இயல்புநிலை 16.',
  'Saving…': 'சேமிக்கிறது…',
  'WhatsApp Receipt Message (English)': 'வாட்ஸ்அப் ரசீது செய்தி (ஆங்கிலம்)',
  'WhatsApp Receipt Message (தமிழ்)': 'வாட்ஸ்அப் ரசீது செய்தி (தமிழ்)',
  'Placeholders: {business} {customer} {customer_id} {amount} {month} {mode} {date} {valid_till} {upi} {phone}': 'இடங்குறிகள்: {business} {customer} {customer_id} {amount} {month} {mode} {date} {valid_till} {upi} {phone}',
  'Tamil block sent below English. Extra placeholders: {month_ta} {mode_ta} {date_ta} {valid_till_ta}': 'தமிழ் பகுதி ஆங்கிலத்திற்கு கீழே அனுப்பப்படும். கூடுதல் இடங்குறிகள்: {month_ta} {mode_ta} {date_ta} {valid_till_ta}',
  'Save Branding': 'பிராண்டிங்கை சேமி',
  'Branding saved!': 'பிராண்டிங் சேமிக்கப்பட்டது!',
  'Failed to save': 'சேமிக்க முடியவில்லை',
  'Business Name': 'வணிகப் பெயர்',
  'Display Phone': 'காட்டப்படும் தொலைபேசி',
  'Care Phone': 'கேர் தொலைபேசி',
  'Care/WhatsApp Phone': 'கேர்/வாட்ஸ்அப் தொலைபேசி',
  'Email': 'மின்னஞ்சல்',
  'GSTIN': 'GSTIN',
  'Monthly UPI ID': 'மாதாந்திர UPI ஐடி',
  'Reconnection UPI ID': 'மறு இணைப்பு UPI ஐடி',
  'Map Latitude': 'வரைபட அட்சரேகை',
  'Map Longitude': 'வரைபட தீர்க்கரேகை',
  'Map Radius (km)': 'வரைபட ஆரம் (கிமீ)',
  'App Name': 'ஆப் பெயர்',
  'e.g. +91 77085 51139': 'எ.கா. +91 77085 51139',
  'e.g. 7708551139': 'எ.கா. 7708551139',
  'For regular monthly payments': 'வழக்கமான மாதாந்திர பணம் செலுத்தல்களுக்கு',
  'For reconnection & receipt': 'மறு இணைப்பு & ரசீதுக்கு',
  'For reconnection & receipt payments': 'மறு இணைப்பு & ரசீது பணம் செலுத்தல்களுக்கு',
  'e.g. 11.0974473': 'எ.கா. 11.0974473',
  'e.g. 77.2013613': 'எ.கா. 77.2013613',
  'e.g. 3': 'எ.கா. 3',
  'e.g. Wasool': 'எ.கா. Wasool',
  'White-label Settings': 'ஒயிட்-லேபிள் அமைப்புகள்',
  'These values are shown across the public website, customer portal, staff panels, and WhatsApp messages.': 'இந்த மதிப்புகள் பொது இணையதளம், வாடிக்கையாளர் போர்டல், ஊழியர் பேனல்கள் மற்றும் வாட்ஸ்அப் செய்திகளில் காட்டப்படும்.',
  'Settings saved!': 'அமைப்புகள் சேமிக்கப்பட்டது!',
  'Save Settings': 'அமைப்புகளை சேமி',

  // ── Operators ──
  'Multi-operator management ({n} operators)': 'பல ஆபரேட்டர் மேலாண்மை ({n} ஆபரேட்டர்கள்)',
  'Add Operator': 'ஆபரேட்டரை சேர்க்க',
  'Search operators...': 'ஆபரேட்டர்களை தேடு...',
  'No matching operators': 'பொருந்தும் ஆபரேட்டர்கள் இல்லை',
  'No operators found': 'ஆபரேட்டர்கள் இல்லை',
  'Operator management is available to master admin only.': 'ஆபரேட்டர் மேலாண்மை மாஸ்டர் நிர்வாகிக்கு மட்டுமே.',
  'Suspended': 'இடைநிறுத்தப்பட்டது',
  'This Month': 'இந்த மாதம்',
  'Staff': 'பணியாளர்கள்',
  'Admin: ': 'நிர்வாகி: ',
  'Reset Password': 'கடவுச்சொல்லை மீட்டமை',
  'Suspend': 'இடைநிறுத்து',
  'Suspend {name}? All staff will be deactivated.': '"{name}"-ஐ இடைநிறுத்தவா? அனைத்து ஊழியர்களும் முடக்கப்படுவார்கள்.',
  'New Operator': 'புதிய ஆபரேட்டர்',
  'Business Name *': 'வணிகப் பெயர் *',
  'Owner Name *': 'உரிமையாளர் பெயர் *',
  'Phone *': 'தொலைபேசி *',
  'Area': 'பகுதி',
  'Customer Prefix *': 'வாடிக்கையாளர் முன்னொட்டு *',
  '2-5 uppercase letters': '2-5 பெரிய எழுத்துக்கள்',
  'Admin Login': 'நிர்வாகி உள்நுழைவு',
  'Username *': 'பயனர்பெயர் *',
  'Password *': 'கடவுச்சொல் *',
  'Creating...': 'உருவாக்குகிறது...',
  'Create Operator': 'ஆபரேட்டரை உருவாக்கு',
  'Reset admin password for': 'இதற்கான நிர்வாகி கடவுச்சொல்லை மீட்டமை',
  'New password': 'புதிய கடவுச்சொல்',
  'Resetting...': 'மீட்டமைக்கிறது...',
  'Failed to create operator': 'ஆபரேட்டரை உருவாக்க முடியவில்லை',
  'Reset failed': 'மீட்டமைப்பு தோல்வி',

  // ── Employees ──
  '{a} active of {b} total': '{a} செயலில், மொத்தம் {b}',
  'Add Employee': 'பணியாளரை சேர்க்க',
  'Search employees...': 'பணியாளர்களை தேடு...',
  'No matching employees': 'பொருந்தும் பணியாளர்கள் இல்லை',
  'No employees found': 'பணியாளர்கள் இல்லை',
  'Role': 'பங்கு',
  'Cannot deactivate admin. Change role first.': 'நிர்வாகியை முடக்க முடியாது. முதலில் பங்கை மாற்றவும்.',
  'Deactivate {name}?': '"{name}"-ஐ முடக்கவா?',
  'Deactivate': 'முடக்கு',
  'Activate': 'செயல்படுத்து',
  'New Employee': 'புதிய பணியாளர்',
  'Full Name *': 'முழு பெயர் *',
  'Min 4 chars': 'குறைந்தது 4 எழுத்துகள்',
  'Service Agent': 'சேவை முகவர்',
  'Create': 'உருவாக்கு',
  'Edit Employee': 'பணியாளரை திருத்து',
  '(cannot change)': '(மாற்ற முடியாது)',
  'Saving...': 'சேமிக்கிறது...',
  'Current Password': 'தற்போதைய கடவுச்சொல்',
  'Set New Password': 'புதிய கடவுச்சொல்லை அமை',
  'New password (min 4 chars)': 'புதிய கடவுச்சொல் (குறைந்தது 4 எழுத்துகள்)',
  'Failed to create employee': 'பணியாளரை உருவாக்க முடியவில்லை',

  // ── Audit Log ──
  '{n} entries recorded': 'பதிவு செய்யப்பட்ட உள்ளீடுகள்: {n}',
  'All Entities': 'அனைத்து வகைகளும்',
  'All Actions': 'அனைத்து செயல்களும்',
  'Customer': 'வாடிக்கையாளர்',
  'Payment': 'பணம் செலுத்தல்',
  'Connection': 'இணைப்பு',
  'Plan': 'திட்டம்',
  'Employee': 'பணியாளர்',
  'Operator': 'ஆபரேட்டர்',
  'ServiceRequest': 'சேவை கோரிக்கை',
  'Reminder': 'நினைவூட்டல்',
  'Setting': 'அமைப்பு',
  'Update': 'புதுப்பி',
  'Loading...': 'ஏற்றுகிறது...',
  'No audit entries found': 'தணிக்கை பதிவுகள் இல்லை',
  'Action': 'செயல்',
  'Entity': 'வகை',
  'Entity ID': 'வகை ஐடி',
  'Changes': 'மாற்றங்கள்',
  'Timestamp': 'நேர முத்திரை',
  'Prev': 'முந்தைய',
  'Page {p} of {t}': 'பக்கம் {p} / {t}',
  'no changes': 'மாற்றங்கள் இல்லை',
  '(+{n} more)': '(+{n} மேலும்)',

  // ── Service Requests ──
  'Open': 'திறந்தது',
  'Assigned': 'ஒதுக்கப்பட்டது',
  'In Progress': 'நடந்து கொண்டிருக்கிறது',
  'Resolved': 'தீர்க்கப்பட்டது',
  'Closed': 'மூடப்பட்டது',
  'Cancelled': 'ரத்து செய்யப்பட்டது',
  'Track and manage customer complaints and service tickets': 'வாடிக்கையாளர் புகார்கள் மற்றும் சேவை டிக்கெட்டுகளை கண்காணித்து நிர்வகிக்கவும்',
  'New Ticket': 'புதிய டிக்கெட்',
  'Tickets ({n})': 'டிக்கெட்டுகள் ({n})',
  'Clear filter': 'வடிகட்டலை அழி',
  'Search tickets...': 'டிக்கெட்டுகளை தேடு...',
  'No matching tickets': 'பொருந்தும் டிக்கெட்டுகள் இல்லை',
  'No service requests found': 'சேவை கோரிக்கைகள் இல்லை',
  'Ticket': 'டிக்கெட்',
  'Priority': 'முன்னுரிமை',
  'Created': 'உருவாக்கப்பட்டது',
  'New Service Ticket': 'புதிய சேவை டிக்கெட்',
  'Search by name or phone...': 'பெயர் அல்லது தொலைபேசி மூலம் தேடு...',
  'Category': 'வகை',
  'Description': 'விவரம்',
  'Describe the issue...': 'பிரச்சனையை விவரிக்கவும்...',
  'Create Ticket': 'டிக்கெட்டை உருவாக்கு',
  'Failed to create ticket': 'டிக்கெட்டை உருவாக்க முடியவில்லை',
  'low': 'குறைவு',
  'medium': 'நடுத்தரம்',
  'high': 'அதிகம்',

  // ── Plans ──
  'Manage pricing plans per MSO': 'ஒவ்வொரு MSO க்கும் விலை திட்டங்களை நிர்வகிக்கவும்',
  'Add Plan': 'திட்டத்தை சேர்க்க',
  'All MSOs': 'அனைத்து MSO களும்',
  'No plans found': 'திட்டங்கள் இல்லை',
  'Plan Name': 'திட்ட பெயர்',
  'Price': 'விலை',
  'MSO Cost': 'MSO செலவு',
  'Validity': 'செல்லுபடி',
  'days': 'நாட்கள்',
  'Edit Plan': 'திட்டத்தை திருத்து',
  'Price (₹)': 'விலை (₹)',
  'MSO Cost (₹)': 'MSO செலவு (₹)',
  'Validity (days)': 'செல்லுபடி (நாட்கள்)',
  'Optional notes': 'விருப்ப குறிப்புகள்',
  'Delete Plan?': 'திட்டத்தை நீக்கவா?',
  'This will deactivate the plan. Existing customers will not be affected immediately.': 'இது திட்டத்தை செயலிழக்கச் செய்யும். தற்போதைய வாடிக்கையாளர்கள் உடனடியாக பாதிக்கப்பட மாட்டார்கள்.',
  'Deleting...': 'நீக்குகிறது...',

  // ── Inventory ──
  'STB Inventory': 'STB இருப்பு',
  'Manage spare, faulty and returned STBs': 'உதிரி, பழுதான மற்றும் திரும்பிய STB களை நிர்வகிக்கவும்',
  'Add STB to Inventory': 'இருப்பில் STB சேர்க்க',
  'Spare': 'உதிரி',
  'Available': 'கிடைக்கும்',
  'Faulty': 'பழுதானது',
  'With MSO': 'MSO இடம்',
  'Loading inventory...': 'இருப்பை ஏற்றுகிறது...',
  'No STBs found in inventory': 'இருப்பில் STB கள் இல்லை',
  'STB No': 'STB எண்',
  'Added': 'சேர்க்கப்பட்டது',
  'Added By': 'சேர்த்தவர்',
  'Edit status': 'நிலையை திருத்து',
  'Remove from inventory': 'இருப்பிலிருந்து நீக்கு',
  'STB Number': 'STB எண்',
  'Notes (optional)': 'குறிப்புகள் (விருப்பம்)',
  'Reason or remarks': 'காரணம் அல்லது குறிப்புகள்',
  'Adding...': 'சேர்க்கிறது...',
  'Add to Inventory': 'இருப்பில் சேர்க்க',
  'Failed to add STB': 'STB சேர்க்க முடியவில்லை',
  'Remove this STB from inventory?': 'இந்த STB-ஐ இருப்பிலிருந்து நீக்கவா?',
  'Removing...': 'நீக்குகிறது...',
  'Remove': 'நீக்கு',

  // ── Notification Bell ──
  'Activity Status': 'செயல்பாட்டு நிலை',
  '{n} new': '{n} புதியது',
  'Mark all read': 'அனைத்தையும் படித்ததாக குறி',
  'No activity notifications yet': 'இன்னும் செயல்பாட்டு அறிவிப்புகள் இல்லை',
  'just now': 'இப்போதுதான்',
  '{n}m ago': '{n} நிமிடம் முன்பு',
  '{n}h ago': '{n} மணி முன்பு',
  '{n}d ago': '{n} நாள் முன்பு',

  // ── StbCopy ──
  'Tap to copy': 'நகலெடுக்க தொடவும்',

  // ── Layout nav & header (not already in dict/layout.ts) ──
  'Collection Map': 'வசூல் வரைபடம்',
  'Record Payment': 'பணம் பதிவு செய்',
  'Operations': 'செயல்பாடுகள்',
  'Surrenders': 'திருப்பி ஒப்படைப்புகள்',
  'Setup & Admin': 'அமைப்பு & நிர்வாகம்',
  'Text Size: {n}%': 'எழுத்து அளவு: {n}%',
  'Collect': 'வசூல்',
  'User': 'பயனர்',
  'Get the app on your home screen for quick access': 'விரைவான அணுகலுக்கு ஆப்பை உங்கள் முகப்புத் திரையில் பெறவும்',
  'Tap': 'தட்டவும்',
  'in Safari bar, then': 'சஃபாரி பட்டியில், பிறகு',
  'Add to Home Screen': 'முகப்புத் திரையில் சேர்க்க',
  'Add to home screen for quick access — works offline': 'விரைவான அணுகலுக்கு முகப்புத் திரையில் சேர்க்க — ஆஃப்லைனில் வேலை செய்யும்',
  'Install App': 'ஆப்பை நிறுவு',
  'New version available': 'புதிய பதிப்பு கிடைக்கிறது',
  'Later': 'பிறகு',
  'Prefix: ': 'முன்னொட்டு: ',
  // Notification Preferences (admin UI)
  'Notification Preferences': 'அறிவிப்பு விருப்பத்தேர்வுகள்',
  'Choose which notification types each staff member receives on their phone.': 'ஒவ்வொரு ஊழியரும் தங்கள் போனில் பெறும் அறிவிப்பு வகைகளைத் தேர்வு செய்யவும்.',
  'Only Admin can manage notification settings.': 'நிர்வாகி மட்டுமே அறிவிப்பு அமைப்புகளை நிர்வகிக்க முடியும்.',
  'No staff users found.': 'ஊழியர் பயனர்கள் எதுவும் இல்லை.',
  'Regular payments play one sound; reconnection alerts play a different sound on your phone.': 'வழக்கமான பணம் செலுத்தல்கள் ஒரு ஒலியும், மறு இணைப்பு எச்சரிக்கைகள் வேறு ஒலியும் இயக்கும்.',
  // Notification type labels (from backend NOTIF_TYPES)
  'Payment Received': 'பணம் பெறப்பட்டது',
  'Reconnection Payment': 'மறு இணைப்பு கட்டணம்',
  'Daily Summary': 'தினசரி சுருக்கம்',
  'STB Swap': 'STB மாற்றம்',
  'Test Notification': 'சோதனை அறிவிப்பு',
};
export default settings;
